name: kpasslib
description: A library to read, modify and write KDBX file format.
version: 1.0.0
# repository: https://github.com/korovan-software/kpasslib

environment:
  sdk: '>=3.4.4'

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.4

dependencies:
  collection: ^1.18.0
  convert: ^3.1.1
  meta: ^1.16.0
  pointycastle: ^3.9.0
  xml: ^6.2.2
